<?php

namespace App\Filament\Resources\AppointmentResource\Pages;

use App\Filament\Resources\AppointmentResource;
use App\Mail\AppointmentMail;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Mail;

class CreateAppointment extends CreateRecord
{
    protected static string $resource = AppointmentResource::class;
    protected static bool $canCreateAnother = false;

    protected function getCreateFormAction(): Action
    {
        return parent::getCreateFormAction()->hidden(); // TODO: Change the autogenerated stub
    }

    protected function getRedirectUrl(): string
    {
        return static::getResource()::getUrl('index'); // TODO: Change the autogenerated stub
    }

    protected function afterCreate()
    {
        $appointment = $this->record;
        Mail::to($appointment->car->customer->email)
            ->queue(new AppointmentMail($appointment));
    }
}
