<?php

namespace App\Filament\Mechanic\Resources\AppointmentResource\Pages;

use App\Filament\Mechanic\Resources\AppointmentResource;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;

class CreateAppointment extends CreateRecord
{
    protected static string $resource = AppointmentResource::class;
    protected static bool $canCreateAnother = false;

    protected function getCreateFormAction(): Action
    {
        return parent::getCreateFormAction()->hidden(); // TODO: Change the autogenerated stub
    }
}
