<?php

namespace App\Filament\Customer\Resources\AppointmentResource\Pages;

use App\Filament\Customer\Resources\AppointmentResource;
use App\Models\Appointment;
use App\Models\User;
use App\Notifications\CustomerAppointmentCreated;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;

class CreateAppointment extends CreateRecord
{
    protected static string $resource = AppointmentResource::class;

    protected static bool $canCreateAnother = false;

    protected function getCreateFormAction(): Action
    {
        return parent::getCreateFormAction()->hidden(); // TODO: Change the autogenerated stub
    }

    protected function getRedirectUrl(): string
    {
        return static::getResource()::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
